platform :ios, '9.0'
use_frameworks!

target 'GitHub-Mobile' do
    pod 'Alamofire'
    pod 'OAuthSwift'
    pod 'Kingfisher'
    pod 'SwiftyJSON'
    pod 'Firebase/Core'
    pod 'Firebase/Database'

end
